name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greating
        run: |
          echo "Hello World!"
          ls -al
      - name: Print goodbye
        run: echo "Goodbye!"
